//1. primary goal of data modelling - to simply data retrieval and manipulation

//2. Data Modeling : The proess of designing the structure of a MongoDb database

//3. MongoDB Transcation - A group of database operations that are executed automatically andindependently of other operations.

//4. Embedded Data Model - A data model that stores data in a single document. Simplifies data retrerival with fewer database queries.

//5. Schema validation : Process of enforcing rules on structure and content of documents in a collection.

//6. REPLICA SET : Supporting multi-document transactions.

//7.Denormalization : The process of adding redundant data to a database to improve read performance. or  Process of duplicating data in a database to improve read performance.

//8. MongoDb Session : To encapsulate a series of operations that are excuted atomically.

//9. unique Index : A type of index that enforces uniqueness on indexed fields.

//10. Sharded Cluster : A type of cluster that distributes data across multiple servers.

//11. Analyzers : A type of index that supports text search. Allows the creation of custom analyzer

//12. $Sort : A query operator that sorts the results of a query.

//13. $Match : A query operator that filters the results of a query.

//14. $Project : A query operator that selects the fields to return in the results of a query.

//15. Creating Index - Improves the performance of read operations.

//16. Compound Index : An index that includes multiple fields.

//17. Text Index : An index that supports text search.

//18. Lucene : A text search engine that supports full-text search. Used by MongoDB to support text search in Mongodb atlas search.

//19. MongoDB Atlas Search : Full search capabilities for MongoDB Atlas.

//20. MongoDb Aggreation : perform data analysis and performnance operations.
